USE oregontrail_db;
INSERT INTO routecard (title, region, quote, category, roll_one, roll_two, roll_three, roll_four, roll_five, roll_six)
VALUES
    ('Easy Trail', '1', '', 'eT','one','two','three','four','five','six'),
    ('Easy Trail', '1', '', 'eT','one','two','three','four','five','six'),
    ('Easy Trail', '1', '', 'eT','one','two','three','four','five','six'),
    ('Easy Trail', '1', '', 'eT','one','two','three','four','five','six'),
    ('Easy Trail', '1', '', 'eT','one','two','three','four','five','six'),
    ('Easy Trail', '1', '', 'eT','one','two','three','four','five','six'),
    ('Easy Trail', '1', '', 'eT','one','two','three','four','five','six'),
    ('Easy Trail', '1', '', 'eT','one','two','three','four','five','six'),
    ('Easy Trail', '1', '', 'eT','one','two','three','four','five','six'),
    ('Easy Trail', '1', '', 'eT','one','two','three','four','five','six'),
    ('Easy Trail', '1', '', 'eT','one','two','three','four','five','six'),
    ('Easy Trail', '1', '', 'eT','one','two','three','four','five','six'),
    ('Easy Trail', '1', '', 'eT','one','two','three','four','five','six'),
    ('Easy Trail', '1', '', 'eT','one','two','three','four','five','six'),
    ('Easy Trail', '1', '', 'eT','one','two','three','four','five','six'),
    ('Difficult Trail', '1', '', 'dT','one','two','three','four','five','six'),
    ('Difficult Trail', '1', '', 'dT','one','two','three','four','five','six'),
    ('Difficult Trail', '1', '', 'dT','one','two','three','four','five','six'),
    ('Difficult Trail', '1', '', 'dT','one','two','three','four','five','six'),
    ('Difficult Trail', '1', '', 'dT','one','two','three','four','five','six'),
    ('Difficult Trail', '1', '', 'dT','one','two','three','four','five','six'),
    ('Difficult Trail', '1', '', 'dT','one','two','three','four','five','six'),
    ('Difficult Trail', '1', '', 'dT','one','two','three','four','five','six'),
    ('Difficult Trail', '1', '', 'dT','one','two','three','four','five','six'),
    ('Difficult Trail', '1', '', 'dT','one','two','three','four','five','six'),
    ('Treacherous Trail', '1', '', 'tT','one','two','three','four','five','six'),
    ('Treacherous Trail', '1', '', 'tT','one','two','three','four','five','six'),
    ('Treacherous Trail', '1', '', 'tT','one','two','three','four','five','six'),
    ('Treacherous Trail', '1', '', 'tT','one','two','three','four','five','six'),
    ('Treacherous Trail', '1', '', 'tT','one','two','three','four','five','six'),
    ('Minor River', '1', '', 'mR','one','two','three','four','five','six'),
    ('Minor River', '1', '', 'mR','one','two','three','four','five','six'),
    ('Minor River', '1', '', 'mR','one','two','three','four','five','six'),
    ('Minor River', '1', '', 'mR','one','two','three','four','five','six'),
    ('Prominent River', '1', '', 'pR','one','two','three','four','five','six'),
    ('Prominent River', '1', '', 'pR','one','two','three','four','five','six'),
    ('Prominent River', '1', '', 'pR','one','two','three','four','five','six'),
    ('Prominent River', '1', '', 'pR','one','two','three','four','five','six'),
    ('Prominent River', '1', '', 'pR','one','two','three','four','five','six'),
    ('Prominent River', '1', '', 'pR','one','two','three','four','five','six'),
    ('Fort', '1', '', 'F','one','two','three','four','five','six'),
    ('Fort', '1', '', 'F','one','two','three','four','five','six'),
    ('Fort', '1', '', 'F','one','two','three','four','five','six'),
    ('Landmark', '1', '', 'L','one','two','three','four','five','six'),
    ('Landmark', '1', '', 'L','one','two','three','four','five','six'),
    ('Landmark', '1', '', 'L','one','two','three','four','five','six'),
    ('Landmark', '1', '', 'L','one','two','three','four','five','six'),
    ('Landmark', '1', '', 'L','one','two','three','four','five','six'),
    ('Landmark', '1', '', 'L','one','two','three','four','five','six'),
    ('Trading Post', '1', '', 'T','one','two','three','four','five','six'),
    ('Trading Post', '1', '', 'T','one','two','three','four','five','six'),
    ('Disaster', '1', '', 'D','one','two','three','four','five','six'),
    ('Disaster', '1', '', 'D','one','two','three','four','five','six'),
    ('Disaster', '1', '', 'D','one','two','three','four','five','six'),
    ('Re-Route', '1', '', 'rR','one','two','three','four','five','six');
    



    
